export function createDefaultState() {
  const now = new Date();
  return {
    version: 1,
    revision: 1,
    lastUpdated: now.toISOString(),
    school: {
      schoolName: "",
      classroomName: "",
      teacherName: "",
      subjectName: "",
      logoDataUrl: "",
    },
    lesson: {
      title: "",
      description: "",
      startTime: "",
      endTime: "",
      status: "aguardando",
      notes: "",
      currentActivity: {
        id: "",
        title: "",
        description: "",
        startTime: "",
        endTime: "",
        color: "#64748b",
        icon: "",
      },
      nextActivity: {
        id: "",
        title: "",
        description: "",
        startTime: "",
        endTime: "",
        color: "#64748b",
        icon: "",
      },
    },
    agenda: [],
    notices: [],
    tasks: [],
    birthdays: [],
    timer: {
      durationSeconds: 25 * 60,
      elapsedBeforeStart: 0,
      startedAt: null,
      pausedAt: null,
      status: "stopped",
      warnedFiveMinutes: false,
      warnedOneMinute: false,
    },
    appearance: {
      theme: "school-blue",
      mode: "light",
      fontScale: 1,
      radius: "rounded",
      density: "comfortable",
      animations: true,
    },
    display: {
      layout: "complete",
      showSeconds: true,
      clockFormat: "24h",
      showDate: true,
      showTeacher: true,
      showSubject: true,
      showAgenda: true,
      showTasks: true,
      showBirthdays: true,
      showMessage: true,
      dailyMessage: "",
      rotateNotices: true,
      noticeRotationSeconds: 8,
      soundsEnabled: false,
      volume: 0.5,
      controlsAutoHideSeconds: 6,
      keepAwake: true,
    },
    history: [],
    pin: { enabled: false, hash: "" },
  };
}
